# -*- coding: utf-8 -*-
"""PP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17xp8Cv5iLOtWrooyPjy57g6hxMlpT_4T
"""

print(input("enter your name"))
print(input("enter your age"))
print(input("date of birth"))
print(input("enter your branch"))
print(input("enter your college name"))

lower=int(input("Enter the lower range:"))
upper=int(input("Enter the upper range:"))
for i in range (lower,upper+1):
    if(i%7==0 and i%5==0):
        print(i)

english = float(input("Please enter English Marks: "))
math = float(input("Please enter Math score: "))
computers = float(input("Please enter Computer Marks: "))
physics = float(input("Please enter Physics Marks: "))
chemistry = float(input("Please enter Chemistry Marks: "))

total = english + math + computers + physics + chemistry
average = total / 5
percentage = (total / 500) * 100

print("\nTotal Marks = %.2f"  %total)
print("Average Marks = %.2f"  %average)
print("Marks Percentage = %.2f"  %percentage)

print("Input lengths of the triangle sides: ")
a = int(input("a: "))
b = int(input("b: "))
c = int(input("c: "))

if a == b == c:
    print("It is an Equilateral triangle")
elif a==b or b==c or c==a:
    print("It is an Isosceles triangle")
else:
    print("It is a Scalene triangle")

# swap two numbers without using temporary variable
x = 10
y = 5

# code to swap
# 'x' and 'y'

if y == 0:
	y = x
	x = 0
elif x == 0:
	x = y
	y = 0
else:
	x = x * y
	y = x // y
	x = x // y


print("After Swapping: x =",
	x, " y =", y)

P = int( input("Please enter value for P: "))
Q = int( input("Please enter value for Q: "))

# To swap the value of two variables
# we will user third variable which is a temporary variable
temp_1 = P
P = Q
Q = temp_1

print ("The Value of P after swapping: ", P)
print ("The Value of Q after swapping: ", Q)

a = 5
b = 6
c = 7
# calculate the semi-perimeter
s = (a + b + c) / 2

# calculate the area
area = (s*(s-a)*(s-b)*(s-c)) ** 0.5
print('The area of the triangle is %0.2f' %area)

def floorSqrt(x):

    # Base cases
    if (x == 0 or x == 1):
        return x

    i = 1
    result = 1
    while (result <= x):

        i += 1
        result = i * i

    return i - 1


x = 11
print(floorSqrt(x))

num1, num2, num3 = 10 , 10000 , 550
max = 0
if num1 >= num2:
    if num1 >= num3:
        print(num1)
elif num2 >= num1:
    if num2 >= num3:
        print(num2)
    else :
        print(num3)

sub1=int(input("Enter marks of the first subject: "))
sub2=int(input("Enter marks of the second subject: "))
sub3=int(input("Enter marks of the third subject: "))
sub4=int(input("Enter marks of the fourth subject: "))
sub5=int(input("Enter marks of the fifth subject: "))
avg=(sub1+sub2+sub3+sub4+sub4)/5
if(avg>=90):
    print("Grade: A")
elif(avg>=80&avg<90):
    print("Grade: B")
elif(avg>=70&avg<80):
    print("Grade: C")
elif(avg>=60&avg<70):
    print("Grade: D")
else:
    print("Grade: F")

def CheckLeap(Year):
  # Checking if the given year is leap year
  if((Year % 400 == 0) or
     (Year % 100 != 0) and
     (Year % 4 == 0)):
    print("Given Year is a leap Year");
  # Else it is not a leap year
  else:
    print ("Given Year is not a leap Year")
# Taking an input year from user
Year = int(input("Enter the number: "))
# Printing result
CheckLeap(Year)

def pypart(n):
	for i in range(0, n):

		for j in range(0, i+1):

			print("* ",end="")
		print("\r")
n = 5
pypart(n)

#find the sum of digits
def getSum(n):

	sum = 0
	while (n != 0):

		sum = sum + int(n % 10)
		n = int(n/10)

	return sum


if __name__ == "__main__":
	n = 789


	print(getSum(n))

from scipy.spatial import distance
p1= (2,2,2)
p2= (1,1,1)
dist = distance.euclidean(p1,p2)
print(dist)

#Check whether a number is palindrome or not
def is_palindrome(n):
    original = n
    reverse = 0
    while n != 0:
        last_digit = n % 10
        reverse = reverse * 10 + last_digit
        n = n // 10

# to check the divisibility of two numbers using boolean function
def is_divisible(n, m):
    """
    Returns True if n is divisible by m, and False otherwise.
    """
    if n % m == 0:
        return True
    else:
        return False
num1 = 10
num2 = 3

if is_divisible(num1, num2):
    print(f"{num1} is divisible by {num2}.")
else:
    print(f"{num1} is not divisible by {num2}.")

# the number is prime or not
def is_prime(num):
  if num <= 1:
    return False
  for i in range(2, int(num**0.5) + 1):
    if num % i == 0:
      return False
  return True

# to check whether the number is in a given range
def in_range(n, start, end):
    while start <= end:
        if start == n:
            return True
        start += 1
    return False

# Example
num = 7
start = 5
end = 10

if in_range(num, start, end):
    print(f"{num} is in the range [{start}, {end}].")
else:
    print(f"{num} is not in the range [{start}, {end}].")

# Armstrong or not using functions
num = int(input())
sum = 0
while num > 0:
    rem = num % 10
    print(pow(rem,3))
    sum += pow(rem,3)
    num //= 10
print(sum)
while sum != num:
    print("It is armstrong number")
    break
if num == sum:
    print("It is armstrong number")
else:
    print("It is not armstrong number")

# given number is perfect or not using functions
def is_perfect_number(n):
  sum = 0
  for i in range(1, n):
    if n % i == 0:
      sum += i
  return sum == n

print(is_perfect_number(6))
print(is_perfect_number(28))

# factorial of the given number
n = int(input("enter a number:"))
factorial = 1
if n >=1:
    for i in range(1,n+1):
        factorial=factorial*i
print("factorial of given numberis:",factorial)

# Function to check if a number is prime
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

#Function to print all prime numbers less than a given number
def print_primes(n):
    for num in range(2, n):
        if is_prime(num):
            print(num)

# Test the function
print_primes(20)

# square of numbers between 1 and 20 (both included).
squares = []
for i in range(1, 21):
    square = i**2
    squares.append(square)
print(squares)

# program to guess a number between 1 and 9.
import random
number = random.randint(1, 9)
while True:
    guess = int(input("Guess a number between 1 and 9: "))
    if guess == number:
        print("Congratulations! You guessed the number correctly!")
        break
    elif guess < number:
        print("Too low! Try again.")
    else:
        print("Too high! Try again.")

# to print grades based on marks.
marks = int(input("Enter your marks: "))

if marks >= 80:
    print("Grade A")
elif marks >= 60:
    print("Grade B")
elif marks >= 50:
    print("Grade C")
else:
    print("Fail")

